name: Build manifest file

on:
  push:
    branches:
      - develop
      - feature/test* # テスト用 確認できたら消す！
    tags:
      - '*'
    paths-ignore:
      - 'gen/**'

jobs:
  kustomize_build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: gt
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.SECRET }}


      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'develop'
          token: ${{ steps.gt.outputs.token }}

      - name: Set environment based on branch
        run: | 
          echo "ENV_TYPE=stg" >> $GITHUB_ENV
          echo "TAG=_stg" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "ENV_TYPE=stg" >> $GITHUB_ENV
            echo "TAG=_stg" >> $GITHUB_ENV
          fi

          if [[ "${{ github.ref }}" =~ ^refs/tags/ ]]; then
            echo "ENV_TYPE=prod" >> $GITHUB_ENV
            echo "TAG=_${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: edit file
        run: uuidgen > gen/test.log

      
      # - name: Add commit and push if changes
      #   run: |
      #     if [[ $(git status -s) != '' ]]; then
      #       git config user.name "github-actions[bot]"
      #       git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #       git add .
      #       git commit -m "edit from ga"
      #       git push origin HEAD
      #     else
      #       echo "No changes"
      #     fi
      #   env:
      #     GITHUB_TOKEN: ${{ steps.gt.outputs.token }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.gt.outputs.token }}
          branch: 'feature/build_kustomize'
          title: 'generate manifest file'
          body: 'This is an generate manifest file pull request.'
          draft: false
          delete-branch: true
          author: user.name "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

      - name: Merge the pull request (if exists)
        run: |
          if [ "${{ steps.cpr.outputs.pull-request-number }}" != "" ]; then
            gh pr merge "${{ steps.cpr.outputs.pull-request-number }}" --merge --auto
          fi
        env:
          GITHUB_TOKEN: ${{ steps.gt.outputs.token }}

      